### PR TITLE
fix: Correctly find artifact when crate has multiple types

### LINKED ISSUE #9: When multiple crate-types are specified, position of cdylib matters when building.
This will not throw an error:
```toml
[lib]
crate-type = ["cdylib", "rlib"]
```
But this will throw an error
```toml
[lib]
crate-type = ["rlib", "cdylib"]
```
and will result in the following output:
```
$ npm run build

> counter@0.1.0 build /myproject
> cargo-cp-artifact -nc index.node -- cargo build --message-format=json-render-diagnostics

warning: dependency (neon) specified without providing a local path, Git repository, or version to use. This will be considered an error in future versions
   Compiling counter v0.1.0 (/myproject)
    Finished dev [unoptimized + debuginfo] target(s) in 0.51s
Did not copy "cdylib:counter"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

### PR DESCRIPTION
**Pull request by kjvalencik**
Resolves: https://github.com/neon-bindings/cargo-cp-artifact/issues/9

[Diff without whitespace](https://github.com/neon-bindings/cargo-cp-artifact/pull/10/files?diff=unified&w=1)

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -62,40 +62,37 @@ You can find instructions for installing Rust and Cargo at:
...
 
-  if (!Array.isArray(kinds) || !kinds.length) {
+  if (!Array.isArray(kinds) || !Array.isArray(filenames)) {
     return;
   }
 
-  const [kind] = kinds;
-  const key = getArtifactName({ artifactType: kind, crateName: name });
-  const outputFiles = options.artifacts[key];
+  kinds.forEach((kind, i) => {
```
Comment (dherman) [inline src/index.js:77]: It'd probably help to write a short comment here that the `kind` and `filenames` fields of the JSON match up pairwise.

**Review by dherman — APPROVED** [review]
Looks good, just one small suggestion for a comment. No need for re-review though.

File: src/index.js (hunk 1 above)
Comment (kjvalencik) [inline src/index.js:77]:
```suggestion
  // `kind` and `filenames` zip up as key/value pairs
  kinds.forEach((kind, i) => {
```
